[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "nautilus-bridge"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "nautilus-trader==2.0.0rc5",
    "dnse-sdk-openapi>=2.0.0",
    "paho-mqtt>=2.1.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "truststore>=0.10.4",
    "websockets>=16.0",
    "msgpack>=1.2.1",
]

[tool.setuptools]
package-dir = { nautilus_bridge = "." }
packages = [
    "nautilus_bridge",
    "nautilus_bridge.instruments",
    "nautilus_bridge.instruments.derivatives",
    "nautilus_bridge.instruments.derivatives.futures",
    "nautilus_bridge.adapters",
    "nautilus_bridge.adapters.entrade",
    "nautilus_bridge.adapters.entrade.api",
]
