[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "strategy"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "core",
    "nautilus-trader==1.231.0",
    "pandas>=2.3.3",
    "numpy",
]

[tool.setuptools]
package-dir = { strategy = "." }
packages = [
    "strategy",
]
