[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "quantcore"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "nautilus-trader==2.0.0rc5",
    "pandas>=2.3.3",
    "numpy",
    "pyarrow",
]

[tool.setuptools]
package-dir = { quantcore = "." }
packages = [
    "quantcore",
]
