[project]
name = "trading"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "market-data",
    "nautilus-trader==2.0.0rc5",
    "dnse-sdk-openapi>=2.0.0",
    "paho-mqtt>=2.1.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "truststore>=0.10.4",
    "websockets>=16.0",
    "msgpack>=1.2.1",
]

[tool.setuptools]
package-dir = { trading = "." }
packages = [
    "trading",
    "trading.adapters",
    "trading.adapters.dnse",
    "trading.adapters.entrade",
]
