[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "quant-api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "trading",
    "nautilus-trader==1.231.0",
    "pandas>=2.3.3",
    "numpy",
    "pyarrow",
]

[tool.setuptools]
package-dir = { quant_api = "." }
packages = [
    "quant_api",
    "quant_api.core",
]
